#!/usr/bin/env bash
# tests/test-plugin-build-pipeline.sh — Validate the build pipeline (Story 13.4)
#
# 13.4a covers the generator only. 13.4b will extend this with full docker-build
# pipeline cases (cache hit/miss, multi-plugin layering, install_script execution,
# build failure surfacing). For now we exercise:
#
#   1. No plugins → generator skips (no Dockerfile.devrail)
#   2. One plugin with a full container block → expected dockerfile shape
#   3. Generator output is byte-identical across re-runs (deterministic)
#   4. Host cache mount: dirs created on host before docker run; root-owned
#      cache files are still readable from the host (review fix M3 fold-in)
#
# Usage: bash tests/test-plugin-build-pipeline.sh
# Env:
#   DEVRAIL_IMAGE  override image name (default: ghcr.io/devrail-dev/dev-toolchain)
#   DEVRAIL_TAG    override image tag  (default: local)

set -euo pipefail

IMAGE="${DEVRAIL_IMAGE:-ghcr.io/devrail-dev/dev-toolchain}:${DEVRAIL_TAG:-local}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKDIR="$(mktemp -d)"

cleanup() {
  if [ -n "${WORKDIR:-}" ] && [ -d "$WORKDIR" ]; then
    docker run --rm -v "$WORKDIR:/cleanup" "$IMAGE" \
      sh -c 'rm -rf /cleanup/* /cleanup/.[!.]* 2>/dev/null || true' >/dev/null 2>&1 || true
    rmdir "$WORKDIR" 2>/dev/null || rm -rf "$WORKDIR" 2>/dev/null || true
  fi
}
trap cleanup EXIT

assert_eq() {
  local expected="$1" actual="$2" context="$3"
  if [ "$expected" != "$actual" ]; then
    echo "FAIL [$context]: expected '$expected', got '$actual'" >&2
    exit 1
  fi
}

# run_generator <loader-cache-host-path> <output-host-path>
# Runs plugin-build-extended-image.sh inside the container with the given cache.
# Sets RUN_EXIT and writes container stderr to RUN_OUT.
run_generator() {
  local cache="$1" out="$2"
  RUN_EXIT=0
  RUN_OUT="$(docker run --rm \
    -v "$cache:/tmp/devrail-plugins-loaded.yaml:ro" \
    -v "$(dirname "$out"):/work" \
    -w /work \
    "$IMAGE" \
    bash /opt/devrail/scripts/plugin-build-extended-image.sh "/work/$(basename "$out")" 2>&1)" ||
    RUN_EXIT=$?
}

# --- Case 1: no plugins → generator skips silently ---
echo "==> Case 1: empty loader cache → generator emits 'no plugins' info, no file"
mkdir -p "$WORKDIR/case1"
cat >"$WORKDIR/case1/cache.yaml" <<'YAML'
plugins: []
YAML
run_generator "$WORKDIR/case1/cache.yaml" "$WORKDIR/case1/Dockerfile.devrail"
assert_eq "0" "$RUN_EXIT" "case1 exit code"
if [ -f "$WORKDIR/case1/Dockerfile.devrail" ]; then
  echo "FAIL [case1]: Dockerfile.devrail should NOT have been generated" >&2
  exit 1
fi
echo "$RUN_OUT" | grep -q "no plugins to extend image with" || {
  echo "FAIL [case1]: expected 'no plugins' info event, got:" >&2
  echo "$RUN_OUT" >&2
  exit 1
}

# --- Case 2: one plugin with full container block → expected dockerfile shape ---
echo "==> Case 2: full container block → dockerfile contains apt/COPY/ENV/RUN"
mkdir -p "$WORKDIR/case2"
cat >"$WORKDIR/case2/cache.yaml" <<'YAML'
plugins:
  - name: elixir
    rev: v1.0.0
    source: github.com/community/devrail-plugin-elixir
    manifest_path: /opt/devrail/plugins/devrail-plugin-elixir/v1.0.0/plugin.devrail.yml
    schema_version: 1
    version: 1.0.0
    devrail_min_version: 1.10.0
    container:
      base_image: elixir:1.17-slim
      apt_packages:
        - inotify-tools
        - libstdc++6
      copy_from_builder:
        - /usr/local/bin/elixir
        - /usr/local/bin/mix
      env:
        MIX_ENV: prod
        ERL_FLAGS: "+S 1"
      install_script: install.sh
    targets:
      lint:
        cmd: "mix credo --strict"
YAML
run_generator "$WORKDIR/case2/cache.yaml" "$WORKDIR/case2/Dockerfile.devrail"
assert_eq "0" "$RUN_EXIT" "case2 exit code"
[ -f "$WORKDIR/case2/Dockerfile.devrail" ] || {
  echo "FAIL [case2]: Dockerfile.devrail not generated" >&2
  echo "$RUN_OUT" >&2
  exit 1
}

generated="$WORKDIR/case2/Dockerfile.devrail"

# Required content checks
grep -qE '^# Auto-generated by plugin-build-extended-image\.sh' "$generated" || {
  echo "FAIL [case2]: missing auto-generated header" >&2
  cat "$generated" >&2
  exit 1
}
grep -qE '^FROM ghcr\.io/devrail-dev/dev-toolchain:' "$generated" || {
  echo "FAIL [case2]: missing FROM line" >&2
  cat "$generated" >&2
  exit 1
}
grep -q "plugin: elixir@v1.0.0" "$generated" || {
  echo "FAIL [case2]: missing plugin section header" >&2
  exit 1
}
grep -q "apt-get install -y --no-install-recommends" "$generated" || {
  echo "FAIL [case2]: missing apt install line" >&2
  exit 1
}
grep -q "inotify-tools" "$generated" || {
  echo "FAIL [case2]: missing apt package" >&2
  exit 1
}
grep -q "COPY --from=elixir:1.17-slim /usr/local/bin/elixir /usr/local/bin/elixir" "$generated" || {
  echo "FAIL [case2]: missing copy_from_builder line" >&2
  exit 1
}
# env values sorted by key (ERL_FLAGS before MIX_ENV)
erl_line="$(grep -n 'ENV ERL_FLAGS' "$generated" | head -1 | cut -d: -f1)"
mix_line="$(grep -n 'ENV MIX_ENV' "$generated" | head -1 | cut -d: -f1)"
if [ -z "$erl_line" ] || [ -z "$mix_line" ] || [ "$erl_line" -ge "$mix_line" ]; then
  echo "FAIL [case2]: env vars not sorted by key (ERL_FLAGS should precede MIX_ENV)" >&2
  cat "$generated" >&2
  exit 1
fi
grep -q "/opt/devrail/plugins/devrail-plugin-elixir/install.sh" "$generated" || {
  echo "FAIL [case2]: missing install_script copy" >&2
  exit 1
}
grep -q "RUN chmod +x .* && bash" "$generated" || {
  echo "FAIL [case2]: missing install_script execution" >&2
  exit 1
}

# --- Case 3: deterministic — re-running produces byte-identical output ---
echo "==> Case 3: deterministic output across re-runs"
hash1="$(sha256sum "$generated" | cut -d' ' -f1)"
run_generator "$WORKDIR/case2/cache.yaml" "$WORKDIR/case2/Dockerfile.devrail"
assert_eq "0" "$RUN_EXIT" "case3 second-run exit code"
hash2="$(sha256sum "$generated" | cut -d' ' -f1)"
assert_eq "$hash1" "$hash2" "case3 dockerfile hash stable across re-runs"

# --- Case 4: host cache directory is created and host-readable ---
# This validates Story 13.4 Task 2 (host cache mount) + the chmod fold-in
# from Story 13.3. Run `make plugins-update` against a local-fs git fixture
# and verify the host can read the cached manifest.
echo "==> Case 4: host cache mount + readable from host"
mkdir -p "$WORKDIR/case4-fixture"
docker run --rm \
  -v "$REPO_ROOT/tests/fixtures/plugin-repos/elixir-v1:/src:ro" \
  -v "$WORKDIR/case4-fixture:/repo" \
  "$IMAGE" \
  sh -c '
    set -e
    cp -a /src/. /repo/
    cd /repo
    git init --quiet
    git config user.email "test@example.com"
    git config user.name "Test"
    git config commit.gpgsign false
    git add -A
    git commit --quiet -m "v1.0.0"
    git tag v1.0.0
  '
mkdir -p "$WORKDIR/case4-ws" "$WORKDIR/case4-host-cache"
cat >"$WORKDIR/case4-ws/.devrail.yml" <<YAML
languages: [elixir]
plugins:
  - source: file://$WORKDIR/case4-fixture
    rev: v1.0.0
    languages: [elixir]
YAML

# Run _plugins-update inside the container with the host Makefile mounted —
# mirroring the harness pattern used by the resolver/loader tests. Mount the
# host cache dir at the cache path the resolver writes to. Mount $WORKDIR
# at the same path inside the container so file:// URLs resolve identically.
case4_out="$(docker run --rm \
  -v "$WORKDIR:$WORKDIR" \
  -v "$WORKDIR/case4-ws:/workspace" \
  -v "$REPO_ROOT/Makefile:/workspace/Makefile:ro" \
  -v "$WORKDIR/case4-host-cache:/opt/devrail/plugins" \
  -e DEVRAIL_VERSION=1.10.0 \
  -w /workspace \
  "$IMAGE" \
  make _plugins-update 2>&1)" || true

# The host cache must contain the resolved manifest, readable by the host user.
manifest="$WORKDIR/case4-host-cache/case4-fixture/v1.0.0/plugin.devrail.yml"
if [ ! -r "$manifest" ]; then
  echo "FAIL [case4]: cached manifest not readable from host: $manifest" >&2
  echo "--- make output ---" >&2
  echo "$case4_out" >&2
  echo "--- host cache listing ---" >&2
  find "$WORKDIR/case4-host-cache" -maxdepth 4 -printf '%y %m %u:%g %p\n' 2>&1 | head -20 >&2
  exit 1
fi

echo "==> All build-pipeline (13.4a) smoke checks passed (4/4)"
