#!/usr/bin/env bash
# scripts/plugin-build-extended-image.sh — Generate Dockerfile.devrail
#
# Purpose: Reads the plugin loader cache (Story 13.2 — full manifest content
#          per plugin merged with resolution metadata) and emits a workspace-
#          local Dockerfile.devrail that extends the core dev-toolchain image
#          with each declared plugin's container fragment (apt_packages,
#          copy_from_builder, env, install_script).
#
# Usage:   bash scripts/plugin-build-extended-image.sh [<output-path>] [--help]
#          Default output: ./Dockerfile.devrail in CWD.
#          Exit 0 — file written, OR no plugins declared (skip silently)
#          Exit 2 — loader cache missing / malformed / no plugins loaded
#
# Dependencies: yq v4+, lib/log.sh, lib/version.sh
#
# Story 13.4a — generator only. Story 13.4b wraps this with `docker build`,
# cache-hit detection, and DOCKER_RUN swap-in.

set -euo pipefail
LC_ALL=C
export LC_ALL

# --- Resolve library path ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVRAIL_LIB="${DEVRAIL_LIB:-${SCRIPT_DIR}/../lib}"

# shellcheck source=../lib/log.sh
source "${DEVRAIL_LIB}/log.sh"
# shellcheck source=../lib/version.sh
source "${DEVRAIL_LIB}/version.sh"

# --- Help ---
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  log_info "plugin-build-extended-image.sh — Generate Dockerfile.devrail"
  log_info "Usage: bash scripts/plugin-build-extended-image.sh [<output-path>]"
  log_info "Default output: ./Dockerfile.devrail in CWD"
  log_info "Exit 0 — file written or no plugins (skip); 2 — cache missing/malformed"
  exit 0
fi

# --- Args ---
OUTPUT_PATH="${1:-./Dockerfile.devrail}"
LOADER_CACHE="${DEVRAIL_PLUGINS_CACHE:-/tmp/devrail-plugins-loaded.yaml}"

require_cmd "yq" "yq is required (v4+)"

if [[ ! -r "${LOADER_CACHE}" ]]; then
  log_event error "loader cache not readable" \
    path="${LOADER_CACHE}" \
    reason="run \`make _plugins-load\` first to populate the cache" \
    language=_plugins
  exit 2
fi

# --- Probe loader cache for plugins ---
plugin_count="$(yq -r '.plugins // [] | length' "${LOADER_CACHE}" 2>/dev/null || echo 0)"
if [[ "${plugin_count}" == "0" ]]; then
  log_event info "no plugins to extend image with; skipping Dockerfile.devrail" \
    cache="${LOADER_CACHE}" language=_plugins
  exit 0
fi

# --- Compute the FROM line ---
# Pin to the exact patch version so cache-hash is stable across local
# invocations. A floating :v1 tag would invalidate every consumer's
# devrail-local:<hash> the moment a new core minor lands.
core_version="$(get_devrail_version)"
if [[ "${core_version}" == "0.0.0-dev" ]]; then
  # Local-dev image — fall back to :local tag (matches DEVRAIL_TAG default).
  base_from="ghcr.io/devrail-dev/dev-toolchain:local"
else
  base_from="ghcr.io/devrail-dev/dev-toolchain:${core_version}"
fi

# --- Generate ---
# Write to a temp file then move atomically so a partial generation can't
# leave a half-written Dockerfile.devrail (concurrent `make check` reads).
output_tmp="${OUTPUT_PATH}.tmp.$$"
trap 'rm -f "${output_tmp}"' EXIT

{
  printf '# Auto-generated by plugin-build-extended-image.sh; DO NOT EDIT.\n'
  printf '# Source-of-truth: .devrail.yml + .devrail.lock + cached plugin manifests.\n'
  printf '# Story 13.4 build pipeline. Extends the core dev-toolchain image with\n'
  printf '# each declared plugin'\''s container fragment.\n'
  printf '#\n'
  printf 'FROM %s AS runtime\n' "${base_from}"
  printf '\n'

  for i in $(seq 0 $((plugin_count - 1))); do
    name="$(yq -r ".plugins[${i}].name" "${LOADER_CACHE}")"
    rev="$(yq -r ".plugins[${i}].rev" "${LOADER_CACHE}")"
    # derive_slug-equivalent: basename of source minus optional .git suffix
    source_url="$(yq -r ".plugins[${i}].source" "${LOADER_CACHE}")"
    slug="$(basename "${source_url}")"
    slug="${slug%.git}"

    printf '# --- plugin: %s@%s (source: %s) ---\n' "${name}" "${rev}" "${source_url}"

    # apt_packages — single RUN that installs and cleans up.
    apt_packages="$(yq -r ".plugins[${i}].container.apt_packages // [] | .[]" "${LOADER_CACHE}" 2>/dev/null | sort -u | tr '\n' ' ' | sed 's/ $//')"
    if [[ -n "${apt_packages}" ]]; then
      printf 'RUN apt-get update && apt-get install -y --no-install-recommends \\\n'
      printf '      %s \\\n' "${apt_packages}"
      printf '    && rm -rf /var/lib/apt/lists/*\n'
    fi

    # copy_from_builder — one COPY per path. Uses the manifest's base_image
    # as the --from source (e.g. `--from=elixir:1.17-slim /usr/local/bin/elixir ...`).
    base_image="$(yq -r ".plugins[${i}].container.base_image // \"\"" "${LOADER_CACHE}")"
    if [[ -n "${base_image}" && "${base_image}" != "null" ]]; then
      copy_paths="$(yq -r ".plugins[${i}].container.copy_from_builder // [] | .[]" "${LOADER_CACHE}" 2>/dev/null || true)"
      while IFS= read -r path; do
        [[ -z "${path}" ]] && continue
        printf 'COPY --from=%s %s %s\n' "${base_image}" "${path}" "${path}"
      done <<<"${copy_paths}"
    fi

    # env — sorted by key for determinism. yq's `to_entries | sort_by(.key)`
    # gives KEY=VALUE pairs.
    env_pairs="$(yq -r ".plugins[${i}].container.env // {} | to_entries | sort_by(.key) | .[] | .key + \"=\" + (.value | tostring)" "${LOADER_CACHE}" 2>/dev/null || true)"
    if [[ -n "${env_pairs}" ]]; then
      while IFS= read -r kv; do
        [[ -z "${kv}" ]] && continue
        printf 'ENV %s\n' "${kv}"
      done <<<"${env_pairs}"
    fi

    # install_script — copy from the cached plugin tree into a known image
    # path so the script doesn't depend on the host cache being mounted at
    # `docker run` time. The relative path inside the cached tree comes
    # from the manifest's container.install_script field.
    install_script_rel="$(yq -r ".plugins[${i}].container.install_script // \"\"" "${LOADER_CACHE}")"
    if [[ -n "${install_script_rel}" && "${install_script_rel}" != "null" ]]; then
      # Absolute source within the build context: the cache is bind-mounted
      # into the build by the wrapper (Story 13.4b). For now we emit a path
      # relative to the cache root, expecting the caller to run docker build
      # with the cache as a build context root or mount.
      cache_path=".devrail-plugins-build/${slug}/${rev}/${install_script_rel}"
      image_path="/opt/devrail/plugins/${slug}/install.sh"
      printf '# Copy install script from build-time cache into the image so\n'
      printf '# subsequent runs do not depend on the host cache being mounted.\n'
      printf 'COPY %s %s\n' "${cache_path}" "${image_path}"
      printf 'RUN chmod +x %s && bash %s\n' "${image_path}" "${image_path}"
    fi
    printf '\n'
  done
} >"${output_tmp}"

mv "${output_tmp}" "${OUTPUT_PATH}"

log_event info "Dockerfile.devrail generated" \
  path="${OUTPUT_PATH}" \
  base_image="${base_from}" \
  plugins:="${plugin_count}" \
  language=_plugins
exit 0
